@startuml
'https://plantuml.com/use-case-diagram

actor bruger

usecase opretBruger
usecase logind

usecase seHovedmenu

usecase tilføjIngrediens

'seRet
usecase vælgRet
usecase opretRet
usecase tilføjTilMadplan

usecase seUge

'seKøleskab
usecase seFryseliste
usecase seIngrediens

'seIndkøbsliste
usecase seVare
usecase fjernVare
usecase tilføjVare

'sehovedmenu
usecase seIndkøbsliste
usecase seMadplan
usecase seKøleskab
usecase seRet


top to bottom direction
bruger --> opretBruger
bruger --> logind

opretBruger --> logind

logind --> seHovedmenu

seHovedmenu <--> seIndkøbsliste
seHovedmenu <--> seMadplan
seHovedmenu <--> seKøleskab
seHovedmenu <--> seRet


seRet --> vælgRet
seRet --> tilføjTilMadplan: en ret
seRet --> opretRet

vælgRet --> seHovedmenu
tilføjTilMadplan --> seHovedmenu

seKøleskab --> seIngrediens
seKøleskab --> seFryseliste
seFryseliste --> seHovedmenu
seIngrediens --> seHovedmenu

seMadplan --> seUge
seUge --> seHovedmenu

seIndkøbsliste --> seVare
seIndkøbsliste --> tilføjVare
seIndkøbsliste --> fjernVare

seVare --> seHovedmenu
tilføjVare --> seHovedmenu
fjernVare --> seHovedmenu

seIngrediens --> seHovedmenu










@enduml