@startuml
'https://plantuml.com/use-case-diagram

actor user

usecase createUser
usecase login
usecase menu
usecase Køleskab
usecase Retter
usecase IndkøbsListe
usecase Madplan
usecase titleListe
usecase tilføjVare
usecase tilføjIngredienser
usecase tilføjRet
usecase brugeRet
usecase SeRetter
usecase vælgTilMadplan
usecase seIngredienser
usecase tastRet
usecase tilføjListe
usecase købt
usecase slet



top to bottom direction
user --> createUser
user --> login

createUser --> login

login --> menu

menu <--> IndkøbsListe
menu <--> Madplan
menu <--> Køleskab
menu <--> Retter

IndkøbsListe <--> titleListe
IndkøbsListe <--> tilføjListe
tilføjListe --> titleListe
titleListe --> slet
titleListe <--> tilføjVare


Madplan --> brugeRet
Madplan <--> tastRet
tastRet --> brugeRet
brugeRet <--> tilføjVare

Retter <--> tilføjRet
Retter <--> SeRetter
SeRetter <--> vælgTilMadplan
vælgTilMadplan --> Madplan

Køleskab <--> tilføjIngredienser
Køleskab <--> seIngredienser

titleListe --> købt
købt --> slet
købt --> tilføjIngredienser





@enduml