@startuml
'https://plantuml.com/use-case-diagram

actor bruger

usecase opretBruger
usecase logind

usecase seHovedmenu



'seRet
usecase vælgRet
usecase opretRet
usecase tilføjTilMadplan

usecase seUge

'seKøleskab
usecase seFryseliste
usecase seIngredienser
usecase tilføjIngrediens

'seIndkøbsliste
usecase fjernVare
usecase tilføjVare
usecase købVare

'sehovedmenu
usecase seIndkøbsliste
usecase seMadplan
usecase seKøleskab
usecase seRet


top to bottom direction
bruger --> opretBruger
bruger --> logind

opretBruger --> logind

logind --> seHovedmenu

seHovedmenu <--> seIndkøbsliste
seHovedmenu <--> seMadplan
seHovedmenu <--> seKøleskab
seHovedmenu <--> seRet


seRet --> vælgRet
seRet --> tilføjTilMadplan: en ret
seRet --> opretRet

vælgRet --> seHovedmenu
tilføjTilMadplan --> seHovedmenu

seKøleskab --> seIngredienser
seKøleskab --> seFryseliste
seFryseliste --> seHovedmenu
seIngredienser --> seHovedmenu

seMadplan --> seUge
seUge --> seHovedmenu


seIndkøbsliste --> tilføjVare
seIndkøbsliste --> fjernVare
seIndkøbsliste --> købVare
købVare --> tilføjIngrediens


tilføjVare --> seHovedmenu
fjernVare --> seHovedmenu

seIngredienser --> seHovedmenu
seKøleskab <--> tilføjIngrediens











@enduml