@startuml
'https://plantuml.com/object-diagram

object Bruger
object indskøbsListe
object Madplan
object Køleskab
object Uge
object Retter
object Vare
object Ingredienser
object fryserListe
object Opskrifter




Bruger *-- indskøbsListe :2
Bruger *-- Madplan: 1
Bruger *-- Køleskab: 1
Bruger *-- Retter: ..999


indskøbsListe o-- Vare

Madplan *-- Uge: 1

Køleskab o-- Ingredienser: ..999
Køleskab o-- fryserListe: 1
fryserListe o-- Vare: ...999
Ingredienser o-- Vare: ...999

Retter o-- Opskrifter
Opskrifter o-- Vare












@enduml