@startuml
'https://plantuml.com/object-diagram

object Bruger
object indskøbsListe
object Madplan
object Køleskab
object titleListe
object Uge
object Retter
object Vare
object Ingredienser
object fryserListe
object Opskrifter




Bruger *-- indskøbsListe
Bruger *-- Madplan
Bruger *-- Køleskab
Bruger *-- Retter

indskøbsListe <|-- titleListe
titleListe o-- Vare

Madplan *-- Uge

Køleskab <|-- Ingredienser
Køleskab <|-- fryserListe
fryserListe <|-- Vare
Ingredienser <|-- Vare

Retter <|-- Opskrifter
Opskrifter o-- Vare












@enduml