@startuml
'https://plantuml.com/class-diagram

package View {
class StartViewForm {
- JTextField brugernavnFelt
- JTextField kodeordFelt
- JButton opretBrugerKnap
- JButton logIndBrugerKnap
- JLabel usernameLabel
- JLabel passwordLabel
+ void LoginForm() {
+ String hentBrugernavn()
+ String hentKodeord()
+ void opretBruger()
+ logIndBruger()
+ void reset(boolean bln)
}

class MainFrame extends JFrame {
- CardLayout cardLayout;
+ DBConnector database = new DBConnector();
+ LoginForm form = new LoginForm();
+ MainFrame()
super("Application")

}

class opretBrugerView {
}
class logIndBrugerVindue {
}
class HovedMenuView {
}
class IndkøbslisteView {
}
class MadplanView {
}
class KøleskabView {
}
class RetView {
}

}

package controller {
class Controller {
- DBConnector database;
- LoginForm form;
+ Controller(LoginForm form, DBConnector database)
+ Bruger brugerOpret = database.opretBruger()
+ Bruger brugerLogInd = database.logIndBruger()
}
}

package domæne {
class DBConnector {
- Bruger nuværendeBruger
+ String brugernavn
+ String password
+ Vare vare
- LoginForm form
- static final String JDBC_DRIVER
- static final String DB_URL
- static final String USER
- static final String PASS
+ DBConnector()
+ Bruger opretBruger()
- void opretKøleskab()
- void opretIndkøbsliste
+ boolean checkCredentialAvailability()
+ void dbConnect()
+ void indstilBrugerNavn(String brugerNavn)
+ String hentBrugernavn()
+ void gemTilListe(Vare vare)
+ hashMap<AProdukt, String> visIndkøbsliste(String brugernavn)>
+ void fjernVare(String vareNavn)

}
}



@enduml